import type { Product, Category, User, Negotiation, Transaction, Wish, WishMatch, Notification, ProductWishMatch } from "./types";

export const categories: Category[] = [
  {
    id: "measurement",
    name: "Measurement Equipment",
    nameJa: "計測機器",
    icon: "gauge",
    subcategories: [
      { id: "gas-analyzer", name: "Gas Analyzer", nameJa: "ガス分析計" },
      { id: "flow-meter", name: "Flow Meter", nameJa: "流量計" },
      { id: "pressure-gauge", name: "Pressure Gauge", nameJa: "圧力計" },
      { id: "thermometer", name: "Thermometer", nameJa: "温度計" },
    ],
    productCount: 156,
  },
  {
    id: "processing",
    name: "Processing Equipment",
    nameJa: "加工機器",
    icon: "cog",
    subcategories: [
      { id: "cnc", name: "CNC Machine", nameJa: "CNCマシン" },
      { id: "lathe", name: "Lathe", nameJa: "旋盤" },
      { id: "milling", name: "Milling Machine", nameJa: "フライス盤" },
    ],
    productCount: 89,
  },
  {
    id: "automation",
    name: "Automation Equipment",
    nameJa: "自動化機器",
    icon: "robot",
    subcategories: [
      { id: "plc", name: "PLC Controller", nameJa: "PLCコントローラー" },
      { id: "robot-arm", name: "Robot Arm", nameJa: "ロボットアーム" },
      { id: "conveyor", name: "Conveyor System", nameJa: "コンベアシステム" },
    ],
    productCount: 124,
  },
  {
    id: "electrical",
    name: "Electrical Equipment",
    nameJa: "電気機器",
    icon: "zap",
    subcategories: [
      { id: "transformer", name: "Transformer", nameJa: "変圧器" },
      { id: "inverter", name: "Inverter", nameJa: "インバーター" },
      { id: "motor", name: "Motor", nameJa: "モーター" },
    ],
    productCount: 203,
  },
  {
    id: "hvac",
    name: "HVAC Equipment",
    nameJa: "空調機器",
    icon: "wind",
    subcategories: [
      { id: "chiller", name: "Chiller", nameJa: "チラー" },
      { id: "air-handler", name: "Air Handler", nameJa: "エアハンドラー" },
      { id: "compressor", name: "Compressor", nameJa: "コンプレッサー" },
    ],
    productCount: 78,
  },
  {
    id: "laboratory",
    name: "Laboratory Equipment",
    nameJa: "研究機器",
    icon: "flask",
    subcategories: [
      { id: "spectrometer", name: "Spectrometer", nameJa: "分光計" },
      { id: "microscope", name: "Microscope", nameJa: "顕微鏡" },
      { id: "centrifuge", name: "Centrifuge", nameJa: "遠心分離機" },
    ],
    productCount: 92,
  },
];

export const products: Product[] = [
  {
    id: "prod-001",
    name: "ガス分析計 GA-500",
    description: "高精度ガス分析計。CO2、O2、N2の同時測定が可能。測定範囲0-100ppm。工場・研究施設向け。校正証明書付き。",
    price: 850000,
    originalPrice: 1200000,
    category: "measurement",
    subcategory: "gas-analyzer",
    manufacturer: "横河電機",
    model: "GA-500",
    year: 2021,
    condition: "used",
    location: "東京都大田区",
    images: ["/products/gas-analyzer-2.jpg", "/products/gas-analyzer-2.jpg", "/products/gas-analyzer-2.jpg", "/products/gas-analyzer-2.jpg"],
    specifications: {
      "測定範囲": "0-100ppm",
      "精度": "±0.5%",
      "応答時間": "30秒以下",
      "電源": "AC100V",
      "寸法": "400×300×200mm",
    },
    sellerId: "seller-001",
    sellerName: "東京機械商事",
    createdAt: "2024-01-15",
    status: "available",
    views: 234,
    favorites: 18,
  },
  {
    id: "prod-002",
    name: "CNC旋盤 NL-2500",
    description: "高速・高精度CNC旋盤。最大加工径φ250mm。Fanuc制御。メンテナンス履歴完備。即稼働可能。",
    price: 4500000,
    originalPrice: 8000000,
    category: "processing",
    subcategory: "cnc",
    manufacturer: "DMG森精機",
    model: "NL-2500",
    year: 2019,
    condition: "used",
    location: "愛知県名古屋市",
    images: ["/products/cnc-lathe-machine-1.jpg", "/products/cnc-lathe-machine-1.jpg", "/products/cnc-lathe-machine-1.jpg", "/products/cnc-lathe-machine-1.jpg"],
    specifications: {
      "最大加工径": "φ250mm",
      "主軸回転数": "6000rpm",
      "制御装置": "Fanuc 0i-TF",
      "電源": "AC200V 3相",
      "重量": "5500kg",
    },
    sellerId: "seller-002",
    sellerName: "中部工機",
    createdAt: "2024-01-10",
    status: "available",
    views: 456,
    favorites: 32,
  },
  {
    id: "prod-003",
    name: "産業用ロボット RV-7FL",
    description: "6軸垂直多関節ロボット。可搬重量7kg。溶接・組立・検査工程に最適。コントローラー付属。",
    price: 1800000,
    originalPrice: 2500000,
    category: "automation",
    subcategory: "robot-arm",
    manufacturer: "三菱電機",
    model: "RV-7FL",
    year: 2020,
    condition: "refurbished",
    location: "大阪府東大阪市",
    images: ["/products/industrial-robot-1.jpg", "/products/industrial-robot-1.jpg", "/products/industrial-robot-1.jpg", "/products/industrial-robot-1.jpg"],
    specifications: {
      "軸数": "6軸",
      "可搬重量": "7kg",
      "リーチ": "717mm",
      "繰返し精度": "±0.02mm",
      "電源": "AC200V",
    },
    sellerId: "seller-003",
    sellerName: "関西オートメーション",
    createdAt: "2024-01-20",
    status: "available",
    views: 189,
    favorites: 15,
  },
  {
    id: "prod-004",
    name: "高圧インバーター V1000",
    description: "省エネ型高圧インバーター。55kW級。ファン・ポンプ制御に最適。通信機能搭載。",
    price: 650000,
    category: "electrical",
    subcategory: "inverter",
    manufacturer: "安川電機",
    model: "V1000",
    year: 2022,
    condition: "new",
    location: "福岡県北九州市",
    images: ["/products/induction-motor-1.jpg", "/products/induction-motor-1.jpg", "/products/induction-motor-1.jpg", "/products/induction-motor-1.jpg"],
    specifications: {
      "定格出力": "55kW",
      "入力電圧": "AC380-480V",
      "制御方式": "ベクトル制御",
      "通信": "Modbus/TCP",
      "保護等級": "IP20",
    },
    sellerId: "seller-004",
    sellerName: "九州電機",
    createdAt: "2024-01-25",
    status: "available",
    views: 123,
    favorites: 8,
  },
  {
    id: "prod-005",
    name: "スクリューコンプレッサー SX-22",
    description: "オイルフリースクリューコンプレッサー。22kW。食品・医薬品工場向け。低騒音設計。",
    price: 1200000,
    originalPrice: 1800000,
    category: "hvac",
    subcategory: "compressor",
    manufacturer: "日立産機",
    model: "SX-22",
    year: 2020,
    condition: "used",
    location: "埼玉県川口市",
    images: ["/products/industrial-chiller-1.jpg", "/products/industrial-chiller-1.jpg", "/products/industrial-chiller-1.jpg", "/products/industrial-chiller-1.jpg"],
    specifications: {
      "出力": "22kW",
      "吐出量": "3.7m³/min",
      "最高圧力": "0.85MPa",
      "騒音値": "68dB",
      "電源": "AC200V 3相",
    },
    sellerId: "seller-005",
    sellerName: "関東空調機器",
    createdAt: "2024-01-18",
    status: "available",
    views: 87,
    favorites: 6,
  },
  {
    id: "prod-006",
    name: "分光光度計 UV-2600",
    description: "紫外可視分光光度計。波長範囲190-900nm。高感度検出器搭載。PC制御ソフト付属。",
    price: 980000,
    category: "laboratory",
    subcategory: "spectrometer",
    manufacturer: "島津製作所",
    model: "UV-2600",
    year: 2021,
    condition: "used",
    location: "京都府京都市",
    images: ["/products/electron-microscope-1.jpg", "/products/electron-microscope-1.jpg", "/products/electron-microscope-1.jpg", "/products/electron-microscope-1.jpg"],
    specifications: {
      "波長範囲": "190-900nm",
      "分解能": "0.1nm",
      "光源": "D2/W",
      "検出器": "光電子増倍管",
      "接続": "USB",
    },
    sellerId: "seller-006",
    sellerName: "京都分析機器",
    createdAt: "2024-01-22",
    status: "available",
    views: 156,
    favorites: 12,
  },
  {
    id: "prod-007",
    name: "流量計 FMG-500",
    description: "電磁流量計。DN50-DN500対応。高精度測定。防水仕様IP67。",
    price: 320000,
    category: "measurement",
    subcategory: "flow-meter",
    manufacturer: "横河電機",
    model: "FMG-500",
    year: 2022,
    condition: "new",
    location: "神奈川県横浜市",
    images: ["/products/flow-meter-2.jpg", "/products/flow-meter-2.jpg", "/products/flow-meter-2.jpg", "/products/flow-meter-2.jpg"],
    specifications: {
      "口径": "DN50-DN500",
      "精度": "±0.35%",
      "流速範囲": "0-10m/s",
      "保護等級": "IP67",
      "出力": "4-20mA",
    },
    sellerId: "seller-001",
    sellerName: "東京機械商事",
    createdAt: "2024-01-28",
    status: "available",
    views: 98,
    favorites: 7,
  },
  {
    id: "prod-008",
    name: "PLCコントローラー Q06HCPU",
    description: "高速PLCコントローラー。プログラム容量60Kステップ。CC-Link対応。",
    price: 180000,
    category: "automation",
    subcategory: "plc",
    manufacturer: "三菱電機",
    model: "Q06HCPU",
    year: 2023,
    condition: "new",
    location: "愛知県豊田市",
    images: ["/products/plc-controller-1.jpg", "/products/plc-controller-1.jpg", "/products/plc-controller-1.jpg", "/products/plc-controller-1.jpg"],
    specifications: {
      "プログラム容量": "60Kステップ",
      "処理速度": "34ns",
      "入出力点数": "4096点",
      "通信": "CC-Link/Ethernet",
      "電源": "DC24V",
    },
    sellerId: "seller-003",
    sellerName: "関西オートメーション",
    createdAt: "2024-01-30",
    status: "available",
    views: 201,
    favorites: 14,
  },
  {
    id: "prod-009",
    name: "圧力トランスミッター PTX-100",
    description: "高精度圧力トランスミッター。測定範囲0-10MPa。4-20mA出力。SUS316L接液部。",
    price: 85000,
    category: "measurement",
    subcategory: "pressure-gauge",
    manufacturer: "横河電機",
    model: "PTX-100",
    year: 2022,
    condition: "new",
    location: "東京都品川区",
    images: ["/products/pressure-transmitter-1.jpg", "/products/pressure-transmitter-1.jpg", "/products/pressure-transmitter-1.jpg", "/products/pressure-transmitter-1.jpg"],
    specifications: {
      "測定範囲": "0-10MPa",
      "精度": "±0.1%",
      "出力": "4-20mA",
      "接液部材質": "SUS316L",
      "保護等級": "IP65",
    },
    sellerId: "seller-001",
    sellerName: "東京機械商事",
    createdAt: "2024-01-12",
    status: "available",
    views: 145,
    favorites: 11,
  },
  {
    id: "prod-010",
    name: "赤外線温度計 IR-500",
    description: "非接触式赤外線温度計。測定範囲-50~500℃。レーザーポインター付き。工業用途向け。",
    price: 45000,
    originalPrice: 65000,
    category: "measurement",
    subcategory: "thermometer",
    manufacturer: "堀場製作所",
    model: "IR-500",
    year: 2021,
    condition: "used",
    location: "京都府京都市",
    images: ["/products/infrared-thermometer-2.jpg", "/products/infrared-thermometer-2.jpg", "/products/infrared-thermometer-2.jpg", "/products/infrared-thermometer-2.jpg"],
    specifications: {
      "測定範囲": "-50~500℃",
      "精度": "±1℃",
      "放射率": "0.1-1.0可変",
      "応答時間": "500ms",
      "電源": "単3電池×2",
    },
    sellerId: "seller-006",
    sellerName: "京都分析機器",
    createdAt: "2024-01-08",
    status: "available",
    views: 78,
    favorites: 5,
  },
  {
    id: "prod-011",
    name: "ポータブルガス検知器 XP-3000",
    description: "可燃性ガス検知器。LEL 0-100%測定。防爆構造。作業現場での安全管理に最適。",
    price: 180000,
    category: "measurement",
    subcategory: "gas-analyzer",
    manufacturer: "新コスモス電機",
    model: "XP-3000",
    year: 2023,
    condition: "new",
    location: "大阪府大阪市",
    images: ["/products/portable-gas-detector-1.jpg", "/products/portable-gas-detector-1.jpg", "/products/portable-gas-detector-1.jpg", "/products/portable-gas-detector-1.jpg"],
    specifications: {
      "検知対象": "可燃性ガス",
      "測定範囲": "0-100%LEL",
      "防爆構造": "本質安全防爆",
      "連続使用": "約20時間",
      "重量": "450g",
    },
    sellerId: "seller-003",
    sellerName: "関西オートメーション",
    createdAt: "2024-01-26",
    status: "available",
    views: 167,
    favorites: 13,
  },
  {
    id: "prod-012",
    name: "超音波流量計 UF-2000",
    description: "クランプオン式超音波流量計。配管を切断せずに設置可能。DN25-DN300対応。",
    price: 480000,
    originalPrice: 650000,
    category: "measurement",
    subcategory: "flow-meter",
    manufacturer: "東京計器",
    model: "UF-2000",
    year: 2020,
    condition: "refurbished",
    location: "東京都板橋区",
    images: ["/products/flow-meter-2.jpg", "/products/flow-meter-2.jpg", "/products/flow-meter-2.jpg", "/products/flow-meter-2.jpg"],
    specifications: {
      "対応口径": "DN25-DN300",
      "精度": "±1%",
      "流速範囲": "0.01-12m/s",
      "出力": "4-20mA/パルス",
      "表示": "LCD",
    },
    sellerId: "seller-001",
    sellerName: "東京機械商事",
    createdAt: "2024-01-14",
    status: "available",
    views: 112,
    favorites: 9,
  },
  {
    id: "prod-013",
    name: "デジタル圧力計 DG-100",
    description: "高精度デジタル圧力計。0.25%精度。データロガー機能付き。",
    price: 125000,
    category: "measurement",
    subcategory: "pressure-gauge",
    manufacturer: "長野計器",
    model: "DG-100",
    year: 2022,
    condition: "new",
    location: "長野県長野市",
    images: ["/products/digital-pressure-gauge-1.jpg", "/products/digital-pressure-gauge-1.jpg", "/products/digital-pressure-gauge-1.jpg", "/products/digital-pressure-gauge-1.jpg"],
    specifications: {
      "測定範囲": "0-1MPa",
      "精度": "±0.25%",
      "メモリ": "10000点",
      "通信": "RS-232C",
      "電源": "AC100V/電池",
    },
    sellerId: "seller-007",
    sellerName: "信州計測機器",
    createdAt: "2024-01-19",
    status: "available",
    views: 89,
    favorites: 7,
  },
  {
    id: "prod-014",
    name: "汎用旋盤 HL-460",
    description: "高剛性汎用旋盤。心間1000mm。チャック付属。教育・小ロット生産向け。",
    price: 980000,
    originalPrice: 1500000,
    category: "processing",
    subcategory: "lathe",
    manufacturer: "滝澤鉄工所",
    model: "HL-460",
    year: 2018,
    condition: "used",
    location: "群馬県太田市",
    images: ["/products/lathe-machine-1.jpg", "/products/lathe-machine-1.jpg", "/products/lathe-machine-1.jpg", "/products/lathe-machine-1.jpg"],
    specifications: {
      "心間": "1000mm",
      "振り": "φ460mm",
      "主軸回転数": "45-1800rpm",
      "モーター": "5.5kW",
      "重量": "2200kg",
    },
    sellerId: "seller-008",
    sellerName: "関東工作機械",
    createdAt: "2024-01-11",
    status: "available",
    views: 234,
    favorites: 18,
  },
  {
    id: "prod-015",
    name: "立型マシニングセンタ VMC-850",
    description: "高速立型マシニングセンタ。主軸12000rpm。BT40。自動工具交換24本。",
    price: 6800000,
    category: "processing",
    subcategory: "milling",
    manufacturer: "牧野フライス",
    model: "VMC-850",
    year: 2020,
    condition: "used",
    location: "静岡県浜松市",
    images: ["/products/vertical-milling-1.jpg", "/products/vertical-milling-1.jpg", "/products/vertical-milling-1.jpg", "/products/vertical-milling-1.jpg"],
    specifications: {
      "テーブルサイズ": "850×450mm",
      "主軸回転数": "12000rpm",
      "主軸テーパー": "BT40",
      "ATC": "24本",
      "制御装置": "Fanuc 31i",
    },
    sellerId: "seller-002",
    sellerName: "中部工機",
    createdAt: "2024-01-23",
    status: "available",
    views: 312,
    favorites: 25,
  },
  {
    id: "prod-016",
    name: "ベルトコンベア BC-500",
    description: "ステンレス製ベルトコンベア。幅500mm×長さ3000mm。食品工場向け。速度可変。",
    price: 380000,
    category: "automation",
    subcategory: "conveyor",
    manufacturer: "三機工業",
    model: "BC-500",
    year: 2021,
    condition: "used",
    location: "千葉県船橋市",
    images: ["/products/belt-conveyor-1.jpg", "/products/belt-conveyor-1.jpg", "/products/belt-conveyor-1.jpg", "/products/belt-conveyor-1.jpg"],
    specifications: {
      "ベルト幅": "500mm",
      "機長": "3000mm",
      "搬送速度": "5-30m/min",
      "材質": "SUS304",
      "モーター": "0.4kW",
    },
    sellerId: "seller-009",
    sellerName: "千葉搬送機器",
    createdAt: "2024-01-17",
    status: "available",
    views: 145,
    favorites: 10,
  },
  {
    id: "prod-017",
    name: "乾式変圧器 500kVA",
    description: "省エネ型乾式変圧器。6600V/200V。低損失設計。ビル・工場向け。",
    price: 2800000,
    category: "electrical",
    subcategory: "transformer",
    manufacturer: "日立産機",
    model: "HT-500D",
    year: 2019,
    condition: "used",
    location: "茨城県日立市",
    images: ["/products/dry-transformer-1.jpg", "/products/dry-transformer-1.jpg", "/products/dry-transformer-1.jpg", "/products/dry-transformer-1.jpg"],
    specifications: {
      "容量": "500kVA",
      "一次電圧": "6600V",
      "二次電圧": "200V",
      "効率": "99%",
      "冷却方式": "自冷式",
    },
    sellerId: "seller-010",
    sellerName: "茨城電機",
    createdAt: "2024-01-09",
    status: "available",
    views: 178,
    favorites: 14,
  },
  {
    id: "prod-018",
    name: "三相誘導モーター 15kW",
    description: "IE3プレミアム効率モーター。15kW 4P。フランジ取付。インバーター対応。",
    price: 185000,
    category: "electrical",
    subcategory: "motor",
    manufacturer: "東芝",
    model: "IKH3-FBKAW21E-4P",
    year: 2023,
    condition: "new",
    location: "東京都府中市",
    images: ["/products/induction-motor-1.jpg", "/products/induction-motor-1.jpg", "/products/induction-motor-1.jpg", "/products/induction-motor-1.jpg"],
    specifications: {
      "出力": "15kW",
      "極数": "4P",
      "効率クラス": "IE3",
      "フレーム": "160M",
      "電圧": "200/400V",
    },
    sellerId: "seller-001",
    sellerName: "東京機械商事",
    createdAt: "2024-01-27",
    status: "available",
    views: 134,
    favorites: 9,
  },
  {
    id: "prod-019",
    name: "チラーユニット 30RT",
    description: "空冷式チラー。冷却能力30RT。R410A冷媒。省エネインバーター搭載。",
    price: 3500000,
    originalPrice: 5200000,
    category: "hvac",
    subcategory: "chiller",
    manufacturer: "ダイキン",
    model: "UWAP300A",
    year: 2019,
    condition: "used",
    location: "大阪府堺市",
    images: ["/products/industrial-chiller-1.jpg", "/products/industrial-chiller-1.jpg", "/products/industrial-chiller-1.jpg", "/products/industrial-chiller-1.jpg"],
    specifications: {
      "冷却能力": "105kW (30RT)",
      "冷媒": "R410A",
      "電源": "AC200V 3相",
      "圧縮機": "スクロール×2",
      "消費電力": "32kW",
    },
    sellerId: "seller-003",
    sellerName: "関西オートメーション",
    createdAt: "2024-01-13",
    status: "available",
    views: 256,
    favorites: 19,
  },
  {
    id: "prod-020",
    name: "エアハンドリングユニット AH-5000",
    description: "外気処理用エアハンドリングユニット。風量5000m³/h。加湿器・冷却コイル付。",
    price: 1650000,
    category: "hvac",
    subcategory: "air-handler",
    manufacturer: "三菱重工",
    model: "AH-5000",
    year: 2020,
    condition: "refurbished",
    location: "兵庫県神戸市",
    images: ["/products/air-handler-1.jpg", "/products/air-handler-1.jpg", "/products/air-handler-1.jpg", "/products/air-handler-1.jpg"],
    specifications: {
      "風量": "5000m³/h",
      "静圧": "500Pa",
      "冷却能力": "45kW",
      "加熱能力": "30kW",
      "フィルター": "中性能",
    },
    sellerId: "seller-011",
    sellerName: "神戸空調設備",
    createdAt: "2024-01-21",
    status: "available",
    views: 98,
    favorites: 7,
  },
  {
    id: "prod-021",
    name: "走査型電子顕微鏡 SEM-3000",
    description: "卓上型走査電子顕微鏡。倍率50-30000倍。真空不要。",
    price: 8500000,
    category: "laboratory",
    subcategory: "microscope",
    manufacturer: "日立ハイテク",
    model: "TM-3000",
    year: 2018,
    condition: "used",
    location: "東京都八王子市",
    images: ["/products/electron-microscope-1.jpg", "/products/electron-microscope-1.jpg", "/products/electron-microscope-1.jpg", "/products/electron-microscope-1.jpg"],
    specifications: {
      "倍率": "50-30000倍",
      "分解能": "30nm",
      "試料サイズ": "φ70mm",
      "真空方式": "低真空",
      "検出器": "BSE",
    },
    sellerId: "seller-006",
    sellerName: "京都分析機器",
    createdAt: "2024-01-16",
    status: "available",
    views: 287,
    favorites: 22,
  },
  {
    id: "prod-022",
    name: "高速遠心分離機 CF-15R",
    description: "冷却遠心分離機。最大15000rpm。温度制御-20~40℃。",
    price: 420000,
    originalPrice: 580000,
    category: "laboratory",
    subcategory: "centrifuge",
    manufacturer: "久保田商事",
    model: "CF-15R",
    year: 2021,
    condition: "used",
    location: "埼玉県さいたま市",
    images: ["/products/lab-centrifuge-1.jpg", "/products/lab-centrifuge-1.jpg", "/products/lab-centrifuge-1.jpg", "/products/lab-centrifuge-1.jpg"],
    specifications: {
      "最大回転数": "15000rpm",
      "最大RCF": "21000×g",
      "温度制御": "-20~40℃",
      "容量": "24×1.5mL",
      "騒音": "54dB",
    },
    sellerId: "seller-012",
    sellerName: "埼玉理化学機器",
    createdAt: "2024-01-24",
    status: "available",
    views: 143,
    favorites: 11,
  },
];

export const mockUsers: User[] = [
  {
    id: "user-001",
    email: "buyer@example.com",
    name: "田中太郎",
    company: "株式会社テスト製造",
    role: "buyer",
    phone: "03-1234-5678",
    address: "東京都品川区",
    verified: true,
    createdAt: "2023-06-15",
  },
  {
    id: "user-002",
    email: "suzuki@example.com",
    name: "鈴木一郎",
    company: "鈴木工業株式会社",
    role: "buyer",
    phone: "06-1234-5678",
    address: "大阪府大阪市",
    verified: true,
    createdAt: "2023-07-20",
  },
  {
    id: "user-003",
    email: "sato@example.com",
    name: "佐藤健一",
    company: "佐藤製作所",
    role: "buyer",
    phone: "052-123-4567",
    address: "愛知県名古屋市",
    verified: true,
    createdAt: "2023-08-10",
  },
  {
    id: "user-004",
    email: "takahashi@example.com",
    name: "高橋美咲",
    company: "高橋エンジニアリング",
    role: "buyer",
    phone: "045-234-5678",
    address: "神奈川県横浜市",
    verified: true,
    createdAt: "2023-09-05",
  },
  {
    id: "user-005",
    email: "yamamoto@example.com",
    name: "山本大輔",
    company: "山本精機株式会社",
    role: "buyer",
    phone: "075-345-6789",
    address: "京都府京都市",
    verified: true,
    createdAt: "2023-10-15",
  },
  {
    id: "user-006",
    email: "ito@example.com",
    name: "伊藤真理",
    company: "伊藤環境テック",
    role: "buyer",
    phone: "011-456-7890",
    address: "北海道札幌市",
    verified: true,
    createdAt: "2023-11-20",
  },
  {
    id: "user-007",
    email: "nakamura@example.com",
    name: "中村誠",
    company: "中村計測システム",
    role: "buyer",
    phone: "092-567-8901",
    address: "福岡県福岡市",
    verified: true,
    createdAt: "2023-12-01",
  },
  {
    id: "seller-001",
    email: "seller@example.com",
    name: "山田花子",
    company: "東京機械商事",
    role: "seller",
    phone: "03-9876-5432",
    address: "東京都大田区",
    verified: true,
    createdAt: "2023-01-10",
  },
];

export const mockNegotiations: Negotiation[] = [
  {
    id: "neg-001",
    productId: "prod-001",
    productName: "ガス分析計 GA-500",
    buyerId: "user-001",
    buyerName: "田中太郎",
    sellerId: "seller-001",
    sellerName: "山田花子",
    status: "pending",
    initialOffer: 750000,
    currentOffer: 750000,
    messages: [
      {
        id: "msg-001",
        senderId: "user-001",
        senderName: "田中太郎",
        content: "この商品に興味があります。750,000円でいかがでしょうか？",
        offer: 750000,
        createdAt: "2024-01-28T10:00:00",
      },
    ],
    createdAt: "2024-01-28T10:00:00",
    updatedAt: "2024-01-28T10:00:00",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "trans-001",
    productId: "prod-010",
    productName: "デジタルマルチメーター DM-500",
    buyerId: "user-001",
    buyerName: "田中太郎",
    sellerId: "seller-002",
    sellerName: "中部工機",
    amount: 45000,
    status: "completed",
    paymentMethod: "銀行振込",
    shippingAddress: "東京都品川区xxx",
    createdAt: "2024-01-15T14:00:00",
    completedAt: "2024-01-20T10:00:00",
  },
];

export const mockWishes: Wish[] = [
  {
    id: "wish-001",
    userId: "user-001",
    userName: "田中太郎",
    title: "ガス分析計を探しています",
    description: "測定範囲0-100ppmのガス分析計を探しています。横河電機製が希望ですが、他メーカーも検討します。",
    criteria: {
      category: "measurement",
      subcategory: "gas-analyzer",
      keywords: ["ガス分析", "ppm"],
      brand: "横河電機",
      priceMax: 1000000,
      condition: ["new", "refurbished"],
    },
    matchThreshold: 60,
    status: "active",
    emailNotification: true,
    createdAt: "2024-01-20T10:00:00",
    updatedAt: "2024-01-20T10:00:00",
    expiresAt: "2024-04-20T10:00:00",
    matchCount: 2,
    lastMatchAt: "2024-01-28T09:00:00",
  },
  {
    id: "wish-002",
    userId: "user-001",
    userName: "田中太郎",
    title: "CNC旋盤 100万円以下",
    description: "小型のCNC旋盤を探しています。予算は100万円以下。中古でも可。",
    criteria: {
      category: "processing",
      subcategory: "lathe",
      keywords: ["CNC", "旋盤"],
      priceMax: 1000000,
      condition: ["new", "used", "refurbished"],
    },
    matchThreshold: 50,
    status: "active",
    emailNotification: false,
    createdAt: "2024-01-22T14:00:00",
    updatedAt: "2024-01-22T14:00:00",
    matchCount: 1,
  },
  {
    id: "wish-003",
    userId: "user-001",
    userName: "田中太郎",
    title: "圧力計 高精度タイプ",
    description: "精度±0.5%以下の高精度圧力計を探しています。",
    criteria: {
      category: "measurement",
      subcategory: "pressure-gauge",
      keywords: ["圧力計", "高精度"],
      priceMax: 200000,
      condition: ["new"],
    },
    matchThreshold: 70,
    status: "paused",
    emailNotification: true,
    createdAt: "2024-01-25T09:00:00",
    updatedAt: "2024-01-26T11:00:00",
    matchCount: 0,
  },
  {
    id: "wish-004",
    userId: "user-002",
    userName: "鈴木一郎",
    title: "高精度ガス測定器を探しています",
    description: "工場排気用のガス測定器。CO2、NOx測定可能なもの希望。",
    criteria: {
      category: "measurement",
      subcategory: "gas-analyzer",
      keywords: ["ガス", "測定", "CO2", "NOx"],
      priceMax: 1500000,
      condition: ["new", "refurbished"],
    },
    matchThreshold: 55,
    status: "active",
    emailNotification: true,
    createdAt: "2024-01-23T11:00:00",
    updatedAt: "2024-01-23T11:00:00",
    matchCount: 1,
    lastMatchAt: "2024-01-28T10:00:00",
  },
  {
    id: "wish-005",
    userId: "user-003",
    userName: "佐藤健一",
    title: "PLCコントローラーを探しています",
    description: "三菱電機のQシリーズPLCを探しています。中古でも状態が良ければ検討します。",
    criteria: {
      category: "control",
      subcategory: "plc",
      keywords: ["PLC", "コントローラー", "三菱"],
      brand: "三菱電機",
      priceMax: 250000,
      condition: ["new", "used", "refurbished"],
    },
    matchThreshold: 60,
    status: "active",
    emailNotification: true,
    createdAt: "2024-01-24T09:00:00",
    updatedAt: "2024-01-24T09:00:00",
    matchCount: 1,
    lastMatchAt: "2024-01-29T09:00:00",
  },
  {
    id: "wish-006",
    userId: "user-004",
    userName: "高橋美咲",
    title: "FA制御機器を探しています",
    description: "工場自動化用の制御機器全般を探しています。",
    criteria: {
      category: "control",
      keywords: ["FA", "制御", "自動化"],
      priceMax: 500000,
      condition: ["new", "used"],
    },
    matchThreshold: 50,
    status: "active",
    emailNotification: false,
    createdAt: "2024-01-25T14:00:00",
    updatedAt: "2024-01-25T14:00:00",
    matchCount: 1,
    lastMatchAt: "2024-01-29T10:00:00",
  },
  {
    id: "wish-007",
    userId: "user-005",
    userName: "山本大輔",
    title: "デジタル圧力計を探しています",
    description: "長野計器製のデジタル圧力計希望。測定範囲0-10MPa。",
    criteria: {
      category: "measurement",
      subcategory: "pressure-gauge",
      keywords: ["圧力計", "デジタル"],
      brand: "長野計器",
      priceMax: 150000,
      condition: ["new"],
    },
    matchThreshold: 65,
    status: "active",
    emailNotification: true,
    createdAt: "2024-01-26T10:00:00",
    updatedAt: "2024-01-26T10:00:00",
    matchCount: 1,
    lastMatchAt: "2024-01-29T11:00:00",
  },
  {
    id: "wish-008",
    userId: "user-006",
    userName: "伊藤真理",
    title: "環境測定機器を探しています",
    description: "大気環境測定用の分析機器を探しています。",
    criteria: {
      category: "measurement",
      keywords: ["測定", "分析", "環境"],
      priceMax: 2000000,
      condition: ["new", "refurbished"],
    },
    matchThreshold: 50,
    status: "active",
    emailNotification: true,
    createdAt: "2024-01-27T09:00:00",
    updatedAt: "2024-01-27T09:00:00",
    matchCount: 1,
    lastMatchAt: "2024-01-29T14:00:00",
  },
  {
    id: "wish-009",
    userId: "user-007",
    userName: "中村誠",
    title: "精度±0.25%以下の計測器",
    description: "高精度な計測器を探しています。圧力計、流量計など。",
    criteria: {
      category: "measurement",
      keywords: ["精度", "計測器", "高精度"],
      priceMax: 300000,
      condition: ["new"],
    },
    matchThreshold: 70,
    status: "active",
    emailNotification: true,
    createdAt: "2024-01-28T08:00:00",
    updatedAt: "2024-01-28T08:00:00",
    matchCount: 1,
    lastMatchAt: "2024-01-29T15:00:00",
  },
  {
    id: "wish-010",
    userId: "seller-001",
    userName: "東京機械商事",
    title: "産業用ロボットアームを探しています",
    description: "6軸以上のロボットアームを探しています。FANUC、安川電機、ABB製を希望。可搬重量10kg以上。",
    criteria: {
      category: "automation",
      subcategory: "robot",
      keywords: ["ロボットアーム", "6軸", "産業用ロボット"],
      brand: "FANUC",
      priceMax: 5000000,
      condition: ["new", "refurbished"],
    },
    matchThreshold: 60,
    status: "active",
    emailNotification: true,
    createdAt: "2024-01-15T09:00:00",
    updatedAt: "2024-01-25T14:00:00",
    expiresAt: "2024-04-15T09:00:00",
    matchCount: 3,
    lastMatchAt: "2024-01-28T16:00:00",
  },
  {
    id: "wish-011",
    userId: "seller-001",
    userName: "東京機械商事",
    title: "高精度CNCフライス盤",
    description: "マキノ、オークマ、DMG森精機の高精度フライス盤を探しています。テーブルサイズ800mm以上希望。",
    criteria: {
      category: "processing",
      subcategory: "milling",
      keywords: ["CNC", "フライス盤", "マシニングセンタ"],
      priceMax: 8000000,
      condition: ["used", "refurbished"],
    },
    matchThreshold: 55,
    status: "active",
    emailNotification: true,
    createdAt: "2024-01-18T11:00:00",
    updatedAt: "2024-01-18T11:00:00",
    matchCount: 1,
    lastMatchAt: "2024-01-27T10:00:00",
  },
  {
    id: "wish-012",
    userId: "seller-001",
    userName: "東京機械商事",
    title: "デジタルオシロスコープ 4ch以上",
    description: "帯域幅500MHz以上のデジタルオシロスコープを探しています。テクトロニクス、キーサイト希望。",
    criteria: {
      category: "measurement",
      subcategory: "oscilloscope",
      keywords: ["オシロスコープ", "デジタル", "500MHz"],
      priceMax: 1500000,
      condition: ["new"],
    },
    matchThreshold: 70,
    status: "paused",
    emailNotification: false,
    createdAt: "2024-01-10T15:00:00",
    updatedAt: "2024-01-20T09:00:00",
    matchCount: 0,
  },
];

export const mockWishMatches: WishMatch[] = [
  {
    id: "match-001",
    wishId: "wish-001",
    productId: "prod-001",
    matchScore: 85,
    matchDetails: {
      categoryMatch: true,
      keywordMatches: ["ガス分析"],
      brandMatch: true,
      modelMatch: false,
      yearInRange: true,
      priceInRange: true,
      conditionMatch: true,
    },
    notified: true,
    notifiedAt: "2024-01-28T09:00:00",
    createdAt: "2024-01-28T09:00:00",
  },
  {
    id: "match-002",
    wishId: "wish-001",
    productId: "prod-011",
    matchScore: 72,
    matchDetails: {
      categoryMatch: true,
      keywordMatches: ["ガス"],
      brandMatch: false,
      modelMatch: false,
      yearInRange: true,
      priceInRange: true,
      conditionMatch: true,
    },
    notified: true,
    notifiedAt: "2024-01-28T10:00:00",
    createdAt: "2024-01-28T10:00:00",
  },
  {
    id: "match-003",
    wishId: "wish-002",
    productId: "prod-014",
    matchScore: 65,
    matchDetails: {
      categoryMatch: true,
      keywordMatches: ["旋盤"],
      brandMatch: false,
      modelMatch: false,
      yearInRange: true,
      priceInRange: true,
      conditionMatch: true,
    },
    notified: false,
    createdAt: "2024-01-28T11:00:00",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-001",
    userId: "user-001",
    type: "wish_match",
    title: "希望条件に合う商品が見つかりました",
    message: "「ガス分析計を探しています」に合致する商品「ガス分析計 GA-500」が出品されました。マッチ度: 85%",
    data: {
      wishId: "wish-001",
      productId: "prod-001",
      matchScore: 85,
    },
    read: false,
    createdAt: "2024-01-28T09:00:00",
  },
  {
    id: "notif-002",
    userId: "user-001",
    type: "wish_match",
    title: "希望条件に合う商品が見つかりました",
    message: "「ガス分析計を探しています」に合致する商品「ポータブルガス検知器 XP-3000」が出品されました。マッチ度: 72%",
    data: {
      wishId: "wish-001",
      productId: "prod-011",
      matchScore: 72,
    },
    read: true,
    createdAt: "2024-01-28T10:00:00",
  },
  {
    id: "notif-003",
    userId: "user-001",
    type: "negotiation",
    title: "交渉に返信がありました",
    message: "「ガス分析計 GA-500」の交渉で売り手から返信がありました。",
    data: {
      negotiationId: "neg-001",
      productId: "prod-001",
    },
    read: false,
    createdAt: "2024-01-28T14:00:00",
  },
  {
    id: "notif-004",
    userId: "seller-001",
    type: "seller_potential_buyer",
    title: "潜在的な購入希望者が見つかりました",
    message: "あなたの出品「ガス分析計 GA-500」に興味を持ちそうな2人の購入希望者がいます。",
    data: {
      productId: "prod-001",
      potentialBuyerCount: 2,
    },
    read: false,
    createdAt: "2024-01-28T15:00:00",
  },
];

export const mockProductWishMatches: ProductWishMatch[] = [
  {
    id: "pwm-001",
    productId: "prod-001",
    wishId: "wish-001",
    wishTitle: "ガス分析計を探しています",
    wishUserId: "user-001",
    wishUserName: "田中太郎",
    matchScore: 85,
    matchDetails: {
      categoryMatch: true,
      keywordMatches: ["ガス分析"],
      brandMatch: true,
      modelMatch: false,
      yearInRange: true,
      priceInRange: true,
      conditionMatch: true,
    },
    contacted: false,
    createdAt: "2024-01-28T09:00:00",
  },
  {
    id: "pwm-002",
    productId: "prod-001",
    wishId: "wish-004",
    wishTitle: "高精度ガス測定器を探しています",
    wishUserId: "user-002",
    wishUserName: "鈴木一郎",
    matchScore: 72,
    matchDetails: {
      categoryMatch: true,
      keywordMatches: ["ガス", "測定"],
      brandMatch: false,
      modelMatch: false,
      yearInRange: true,
      priceInRange: true,
      conditionMatch: true,
    },
    contacted: true,
    createdAt: "2024-01-28T10:00:00",
  },
  {
    id: "pwm-003",
    productId: "prod-009",
    wishId: "wish-003",
    wishTitle: "圧力計 高精度タイプ",
    wishUserId: "user-001",
    wishUserName: "田中太郎",
    matchScore: 78,
    matchDetails: {
      categoryMatch: true,
      keywordMatches: ["圧力計", "高精度"],
      brandMatch: false,
      modelMatch: false,
      yearInRange: true,
      priceInRange: true,
      conditionMatch: true,
    },
    contacted: false,
    createdAt: "2024-01-28T11:00:00",
  },
  {
    id: "pwm-004",
    productId: "prod-007",
    wishId: "wish-005",
    wishTitle: "PLCコントローラーを探しています",
    wishUserId: "user-003",
    wishUserName: "佐藤健一",
    matchScore: 91,
    matchDetails: {
      categoryMatch: true,
      keywordMatches: ["PLC", "コントローラー", "三菱"],
      brandMatch: true,
      modelMatch: true,
      yearInRange: true,
      priceInRange: true,
      conditionMatch: true,
    },
    contacted: false,
    createdAt: "2024-01-29T09:00:00",
  },
  {
    id: "pwm-005",
    productId: "prod-007",
    wishId: "wish-006",
    wishTitle: "FA制御機器を探しています",
    wishUserId: "user-004",
    wishUserName: "高橋美咲",
    matchScore: 68,
    matchDetails: {
      categoryMatch: true,
      keywordMatches: ["FA", "制御"],
      brandMatch: false,
      modelMatch: false,
      yearInRange: true,
      priceInRange: true,
      conditionMatch: true,
    },
    contacted: true,
    createdAt: "2024-01-29T10:00:00",
  },
  {
    id: "pwm-006",
    productId: "prod-012",
    wishId: "wish-007",
    wishTitle: "デジタル圧力計を探しています",
    wishUserId: "user-005",
    wishUserName: "山本大輔",
    matchScore: 82,
    matchDetails: {
      categoryMatch: true,
      keywordMatches: ["圧力計", "デジタル"],
      brandMatch: true,
      modelMatch: false,
      yearInRange: true,
      priceInRange: true,
      conditionMatch: true,
    },
    contacted: false,
    createdAt: "2024-01-29T11:00:00",
  },
  {
    id: "pwm-007",
    productId: "prod-001",
    wishId: "wish-008",
    wishTitle: "環境測定機器を探しています",
    wishUserId: "user-006",
    wishUserName: "伊藤真理",
    matchScore: 65,
    matchDetails: {
      categoryMatch: true,
      keywordMatches: ["測定", "分析"],
      brandMatch: false,
      modelMatch: false,
      yearInRange: true,
      priceInRange: false,
      conditionMatch: true,
    },
    contacted: false,
    createdAt: "2024-01-29T14:00:00",
  },
  {
    id: "pwm-008",
    productId: "prod-012",
    wishId: "wish-009",
    wishTitle: "精度±0.25%以下の計測器",
    wishUserId: "user-007",
    wishUserName: "中村誠",
    matchScore: 88,
    matchDetails: {
      categoryMatch: true,
      keywordMatches: ["精度", "計測器"],
      brandMatch: true,
      modelMatch: false,
      yearInRange: true,
      priceInRange: true,
      conditionMatch: true,
    },
    contacted: false,
    createdAt: "2024-01-29T15:00:00",
  },
];
